//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArbeitsPlanung4Lib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArbeitsPlaung4ModelContainer : DbContext
    {
        public ArbeitsPlaung4ModelContainer()
            : base("name=ArbeitsPlaung4ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzer> BenutzerSet { get; set; }
        public virtual DbSet<Flugzeug> FlugzeugSet { get; set; }
        public virtual DbSet<Arbeit> ArbeitSet { get; set; }

    }
}
